### ISSUE TITLE
Error While Dumping

### ISSUE THREAD

**Issue by justinmc** [jdonaldson/vaxe#101]
I'm getting an error every time I try to quit vim after installing the plugin on neovim via vim-plug:

```
E951: Error while dumping variable g:C, itself: attempt to dump function reference
E574: Failed to write variable C
```

**Comment by DocWinter** [comment]
Yep, I've the same issues as you. But I don't know where it comes from.

**Comment by deathbeam** [comment]
It is coming from this [line](https://github.com/jdonaldson/vaxe/blob/master/plugin/haxe.vim#L69). Basically, renaming this variable to something more specific will solve it. Here is [explanation](https://github.com/neovim/neovim/issues/3721) from neovim issue tracker.

**Comment by jdonaldson** [comment]
Oh ok, I'll come up with a different proxy then.

**Comment by jdonaldson** [comment]
Try updating and see if this change helps : https://github.com/jdonaldson/vaxe/commit/d9792648583e0648f07a1efa6ec0f98c6f010b81

**Comment by deathbeam** [comment]
Awesome, for me it is now working perfectly :smile:

**Comment by jdonaldson** [comment]
I'm claiming victory then, thanks for pinpointing the issue.
