### ISSUE TITLE
g:vaxe_completion_require_autowrite can't be set by user

### ISSUE THREAD

**Issue by dburburan** [jdonaldson/vaxe#102]
Hi,

When vaxe initialises, the line below mixes up `completion_require` and `require_completion`, making it override any user preference

```
let g:vaxe_completion_require_autowrite 
            \=C('g:vaxe_require_completion_autowrite', 1) 
```

All the best,
David

**Comment by jdonaldson** [comment]
Thanks for this, fixed.
