### ISSUE TITLE
Bunch of error messages

### ISSUE THREAD

**Issue by flamendless** [jdonaldson/vaxe#111]
Hey, ive installed `vaxe` using `Vundle`.

Opening a `.hx` file shows this error on vim startup
```
Error detected while processing /home/brbl/.vim/bundle/vaxe/ftplugin/haxe.vim:
line   35:
E121: Undefined variable: g:airline_statusline_funcrefs
E116: Invalid arguments for function add
E121: Undefined variable: g:airline_statusline_funcrefs
E116: Invalid arguments for function add
```

Note, i am using airline. Ive tried adding `let g:vaxe_enable_airline = 0` in my `.vimrc`, does not do anything

**Comment by schmidh** [comment]
Could you find a solution?

**Comment by flamendless** [comment]
@schmidh nope. This plugin isnt maintained I suppose

_Sent from my HUAWEI GR5 2017 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by schmidh** [comment]
Only when you try to open a haxe file from the command line this error happens. From within vim everything works fine. Problem is that airline has not been loaded when the code in haxe.vim runs. One could check to see if the global variable g:airline_statusline_funcrefs exists and if not, then don't call the add function. Then you wouldn't have status line information as the code for airline will be called afterwards. Seems like a catch 22. At least one would not get an error message.

I tried also with VAM and added a addon-info.json file as it has some sort of dependency management built in. But didn't help either.

**Comment by jdonaldson** [comment]
Thanks for the detail there.  Sounds like a bug with airline?

**Comment by jdonaldson** [comment]
I see a problem with the readme, can you try this?

```viml
let g:vaxe_enable_airline_defaults = 0
```

**Comment by schmidh** [comment]
Hi Justin,

sorry for the long delay.

It works! Thanks a lot.
