### ISSUE TITLE
SyntasticCheck doesn't report errors (OSX)

### ISSUE THREAD

**Issue by thoughton** [jdonaldson/vaxe#53]
Hi,

I'm a new Vaxe user, and I'm having trouble getting Syntastic to work in MacVim on OSX.

I tend to install most OS packages (MacVim, Haxe, etc.) using Homebrew, and Vim plugins (Vaxe, Syntastic, etc.) using Vundle.

Vaxe seems to mostly be working, as it asks me to choose a target when I open my .hx file, and the ```:make``` command works.

Moreover, if I do ```:SyntasticInfo``` it gives what I think is the expected output:
```
Syntastic: active mode enabled
Syntastic info for filetype: haxe
Available checker(s): haxe
Currently enabled checker(s): haxe
Press ENTER or type command to continue
```
However, when I do ```:SyntasticCheck``` or ```:SyntasticCheck haxe``` nothing seems to happen.  Even if I add intentional errors into the code - errors that cause the ```:make``` command to fail - it still fails to give any output.

(Incidentally, ```:SyntasticCheck``` works fine on a C++ project. Using a gcc checker, I believe.)

Any help or advice would be appreciated!

**Comment by jdonaldson** [comment]
Closing this out, let me know if you see it again.
