### ISSUE TITLE
Better help render?

### ISSUE THREAD

**Issue by gerroon** [jdonaldson/vaxe#69]
Hi

I like the help window however it looks like the original help is in html so the rendering totally off (renders as text) I wonder if it would be possible to use a middle man program like w3m or lynx (at least on linux) to render the html as text before showing it. Not sure if there is already a way to render html as nice text in Vim.

thanks for the extension

**Comment by jdonaldson** [comment]
Thanks for trying it out!

I already do a few things to try and clean up the text.  But, some haxe docs have inserted markdown references, html, you name it.  I probably can make a pass at stripping it out.

**Comment by gerroon** [comment]
Thanks for looking into it.

Btw how do I scroll up and down while the autocomplete is on and the help page is on? Some pages are longer so not sure how I can manage to kep both open at the same time.

thanks

**Comment by jdonaldson** [comment]
do you want to scroll the page, or scroll the selection of completion options?

also note:  I've turned off the help page text by default in my personal config... eventually you don't need to see it, and it saves you some space.  Check the "misc config" section in the readme.

**Comment by gerroon** [comment]
I want to read the help while the scrool is open since I can read and go up and down to see what I need.

**Comment by jdonaldson** [comment]
the help should stay open... do you have a plugin or some other setting that is closing it?

**Comment by gerroon** [comment]
not sure, i have neocomplcache.vim but the library methods and functions do not show up so I use c-x c-o to ppen the pull down menu.

**Comment by jdonaldson** [comment]
Added a patch to close your original issue, but I'll leave this open a while longer for your other issue.

regarding scrolling... are you by chance scrolling your terminal window instead of your vim buffer? That's the simplest way I can think that this is happening.

**Comment by gerroon** [comment]
thanks.

Well I am on Gvim when I click on the help buffer I loose the completion pulldown window

**Comment by jdonaldson** [comment]
I think you'll need to look at general vim help for this, I don't see anything I can do on my end.
