### ISSUE TITLE
Vaxe suddenly started complaning about compiler not finding libs

### ISSUE THREAD

**Issue by gerroon** [jdonaldson/vaxe#71]
Hi

I had to reinstall Haxe and Openfl from scratch (as described on Openfl's website). My openfl projects work and compile alright after the install. However Vaxe started complaning that it can't find openfl.Lib. I disable it and then it complaints about the next lib in line when I use C-x C-o omni complete. So I am not sure what is going on. 

The only thing I had to do different is to symlink the haxe folder under /usr/lib/haxe due to system drive space restrictions, but still openfl compiles fine no issue 

edit: I just tested the symlink issue and I doubt it is the case. I copied the actual folders and still the same.

OpenFL Command-Line Tools (3.0.0-beta.3-LNagLR)
Haxe Compiler 3.1.3 - (C)2005-2014 Haxe Foundation

**Comment by gerroon** [comment]
Ok out of desperation I deleted the project.xml.hxml and Vaxe is back.

**Comment by jdonaldson** [comment]
yes, I need to put in a utility method for this.  Vaxe can't detect big changes in the env like that (although it may be possible), and so it won't regenerate the hxml.  At the very least, I should add a straightforward command to regenerate the hxml, and add a small FAQ section about how to handle this situation.

**Comment by gerroon** [comment]
@jdonaldson 

It would be very nice to have the command , otherwise it seems like the only way is to delete it and restart vim? 

I also realized that this is an issue when adding a new library to the project.xml. 

Thanks again for great addon. It is very helpful

**Comment by jdonaldson** [comment]
I added a "LimeRebuildHxml" command, and a corresponding version for Flow.  Let me know if this works for you.

**Comment by gerroon** [comment]
Ok thanks I will test it out when I can
