### ISSUE TITLE
Omni-Completion error on Windows

### ISSUE THREAD

**Issue by sys9kdr** [jdonaldson/vaxe#78]
Omni-Completion fails by compile error when typed `<C-x><C-o>` on import standard libraries(e.g. input `import js.` and try to complete). Error message is "Compile Error: The filename, directory name, or volume label syntax is incorrect".

This issue happens on

- Windows 8.1, 32bit
- Vim 7.4
- Python 2.7.10

Does anyone has a same issue on Windows?

**Comment by nadako** [comment]
Yeah same here. I'm trying to use Vim every once in a while and always there's some problem :(

**Comment by nadako** [comment]
It seems that windows `cmd` doesn't really like the `;` as command separator.

**Comment by jdonaldson** [comment]
thanks for the heads up. windows support is admittedly lousy.  I don't do any dev on windows machines anymore, and have been too lazy to set up bootcamp.  I'll look into getting a vm or something I can test on quickly.

**Comment by nadako** [comment]
It seems that on windows cmd, you have to use `&` instead (see http://www.microsoft.com/resources/documentation/windows/xp/all/proddocs/en-us/ntcmds_shelloverview.mspx?mfr=true)
