### ISSUE TITLE
Undefined variable: main_syntax

### ISSUE THREAD

**Issue by danbruegge** [jdonaldson/vaxe#85]
Hi, after some months not using haxe. I try to start a new project.

I moved from vim to neovim. Reinstalled vaxe and every start of neovim with a haxe file will show this errors: 
![vaxe-error-0](https://cloud.githubusercontent.com/assets/1296438/11040785/42efd09e-870e-11e5-8c67-5e9a7b11097b.png)

My nvimrc settings for vaxe:
```
let g:vaxe_cache_server = 1
let g:vaxe_lime_target = "linux -neko -64"
```

Regards, Dan

**Comment by danbruegge** [comment]
push. no one can help?

**Comment by jdonaldson** [comment]
I've been on vacations,  I'll check into this soon.

**Comment by danbruegge** [comment]
Thanks. :)

**Comment by danbruegge** [comment]
Solved in https://github.com/jdonaldson/vaxe/commit/a0f8b4dc588c78aaa0342a081a138283242caeea

Thanks. :)

**Comment by jdonaldson** [comment]
You're very welcome.  Good to know this is working for neovim, I'm going to start using that more.

**Comment by danbruegge** [comment]
:) Currently i tested it only on my machine on work, where i don't use haxe. So i only touched a new file and opened with nvim. On the evening i'll test it also @home.

**Comment by danbruegge** [comment]
Ok, problem still existis, if i use vaxe with `Plug 'jdonaldson/vaxe', { 'for': 'haxe' }`.

It disappears if i use the plugin with `Plug 'jdonaldson/vaxe'`

**Comment by jdonaldson** [comment]
the "for" designation in the Plug config is a bit nonstandard.  My guess is that it is preventing some of the global vaxe config logic from working.  Vaxe works on hxml, hx, and hss, as well as providing some project-specific functionality (e.g. it tries to see if you are working on an openfl project).  So, it is doing useful things even if you're not working on an hx file.  I should mention that I took care for it not to add significant overhead for non-haxe development, so there's really no reason to prevent it from loading and running normally.

**Comment by danbruegge** [comment]
Ok, thanks for the info. :)
