### ISSUE TITLE
Feature request: disable automatic hxml search with config variable

### ISSUE THREAD

**Issue by infidel-** [jdonaldson/vaxe#87]
I have a project that does not have any hxml files in it, only Makefile. Opening (or switching to) any .hx files will trigger the error "Project build file not valid, please create one."

I have to manually comment out the line

```
call vaxe#AutomaticHxml()
```

to skip the errors of this kind.

**Comment by infidel-** [comment]
There is another problem here. Please disable auto-setting makeprg if the build directory contains Makefile. This breaks the ":make" command in case when the Makefile contains more instructions apart from "haxe XXX.hxml".

**Comment by gogoprog** [comment]
Hello
I also have a Makefile and I'd like to disable the vaxe build process
