### ISSUE TITLE
Completion with Kha

### ISSUE THREAD

**Issue by Jumblemuddle** [jdonaldson/vaxe#96]
Has anyone had luck setting up vaxe for kha development?

`Compiler error: No valid build file`

**Comment by OvermindDL1** [comment]
Nope, Kha does not follow any kind of standards for its build system.  Heck, it uses *node* of all things for its build system...

**Comment by Jumblemuddle** [comment]
Thanks, @OvermindDL1

**Comment by RobDangerous** [comment]
Thanks from me as well, @OvermindDL1

**Comment by OvermindDL1** [comment]
Not to say it cannot be added for note, just no one has done so yet.

**Comment by jdonaldson** [comment]
So, for the other build systems (snow, openfl) there's a somewhat complex startup process that looks for project specific build files, and then infers what to do.  E.g., a project.xml file infers an OpenFL project, a *.flow project infers a Flow project.  So, the first step may be to identify the "giveaway" file for a kha project.  What's the file to look for?

**Comment by OvermindDL1** [comment]
I've only recently started using Kha (loving its system structure, starting to understand its build system though I still dislike javascript (I prefer typed languages)).  But the key file to look for I'd say would be "khafile.js" from what I've seen this far.  I'd quite love a PR to add support.  :-)

**Comment by RobDangerous** [comment]
khafile.js it is indeed.

**Comment by jdonaldson** [comment]
that should get me started, thanks.
